spring.batch.job.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=create-drop
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always
file.upload-dir=app/tmp
product.api.url=http://localhost:8082/product/add/all

spring.datasource.schema=classpath:schema.sql
server.port=8080


