spring.application.name=order

server.port=8083

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/order
spring.datasource.username=postech
spring.datasource.password=postech

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=create-drop


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq

spring.cloud.stream.binders.rabbit.type=rabbit
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.host=${spring.rabbitmq.host}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.port=${spring.rabbitmq.port}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.username=${spring.rabbitmq.username}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.password=${spring.rabbitmq.password}

spring.cloud.stream.default.contentType=application/json

spring.cloud.stream.defaultBinder=rabbit

# Definicao de funcoes
spring.cloud.stream.function.definition=PaymentCreatedEventListner; paymentUpdatedEventListner

# Bindings das streams - Consumer
spring.cloud.stream.bindings.paymentCreatedEventListner-in-0.destination=payment.v1.event.payment-created
spring.cloud.stream.bindings.paymentCreatedEventListner-in-0.group=payment-order

#Producer
spring.cloud.stream.bindings.paymentUpdatedEventListner-out-0.destination=order.v1.event.payment-updated
spring.cloud.stream.bindings.paymentUpdatedEventListner-in-0.destination=order.v1.event.payment-updated

# Configuracoes especificas do RabbitMQ
spring.cloud.stream.rabbit.bindings.paymentCreatedEventListner-in-0.consumer.auto-bind-dlq=true

# Urls Apps
URL_CUSTOMER=http://localhost:8081/customer
URL_PAYMENTS=http://localhost:8086/payments
URL_PRODUCT=http://localhost:8082/product
URL_DELIVERY=http://localhost:8084/delivery