spring.application.name=payment

server.port=8086

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/payment
spring.datasource.username=postech
spring.datasource.password=postech

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=create-drop
spring.cloud.stream.default.contentType=application/json


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq

spring.cloud.stream.binders.rabbit.type=rabbit
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.host=${spring.rabbitmq.host}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.port=${spring.rabbitmq.port}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.username=${spring.rabbitmq.username}
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.password=${spring.rabbitmq.password}

spring.cloud.stream.defaultBinder=rabbit


# Definição de funções
spring.cloud.stream.function.definition=PaymentEventGatewayWithStream; paymentUpdatedEventListner
#Producer pagamento
spring.cloud.stream.bindings.paymentCreatedEventListner-out-0.destination=payment.v1.event.payment-created
spring.cloud.stream.bindings.paymentCreatedEventListner-in-0.destination=payment.v1.event.payment-created

#Consumer
spring.cloud.stream.bindings.paymentUpdatedEventListner-in-0.destination=order.v1.event.payment-updated
spring.cloud.stream.bindings.paymentUpdatedEventListner-out-0.destination=order.v1.event.payment-updated
spring.cloud.stream.bindings.paymentCreatedEventListner-in-0.group=payment
